#!/usr/bin/env node
'use strict';

/**
 * Generates v8-cli command files from the Swagger admin API spec.
 *
 * Usage:
 *   node scripts/codegen.js                          # uses saved spec
 *   node scripts/codegen.js http://localhost:3003     # fetches live spec
 *
 * Output: src/commands/gen-*.js (one per resource group)
 *
 * These generated files are meant to be reviewed and committed.
 * The codegen is idempotent — re-running overwrites gen-* files.
 */

const fs = require('fs');
const path = require('path');
const http = require('http');
const https = require('https');

const SPEC_FILE = path.join(__dirname, 'admin-spec.json');
const OUT_DIR = path.join(__dirname, '..', 'src', 'commands');

// ── Helpers ──────────────────────────────────────────────────────────

function fetchSpec(baseUrl) {
  return new Promise((resolve, reject) => {
    const url = `${baseUrl}/api-docs-json`;
    const lib = url.startsWith('https') ? https : http;
    lib.get(url, (res) => {
      let d = '';
      res.on('data', (c) => (d += c));
      res.on('end', () => {
        const spec = JSON.parse(d);
        const adminPaths = {};
        for (const [p, methods] of Object.entries(spec.paths)) {
          if (p.includes('/admin')) adminPaths[p] = methods;
        }
        resolve({ paths: adminPaths, components: spec.components });
      });
    }).on('error', reject);
  });
}

function resolveSchema(ref, components) {
  if (!ref) return {};
  const name = ref.split('/').pop();
  return components?.schemas?.[name] || {};
}

function getBodyFields(op, components) {
  const schema = op.requestBody?.content?.['application/json']?.schema;
  if (!schema) return [];
  const dto = schema.$ref ? resolveSchema(schema.$ref, components) : schema;
  if (!dto.properties) return [];
  return Object.entries(dto.properties).map(([key, val]) => ({
    key,
    type: val.type || (val.enum ? 'enum' : 'any'),
    enum: val.enum,
    required: (dto.required || []).includes(key),
    description: val.description || '',
    isArray: val.type === 'array',
  }));
}

function getQueryParams(op) {
  return (op.parameters || [])
    .filter((p) => p.in === 'query')
    .map((p) => ({
      key: p.name,
      required: p.required || false,
      type: p.schema?.type || 'string',
      enum: p.schema?.enum,
      default: p.schema?.default,
      description: p.description || '',
    }));
}

function getPathParams(op) {
  return (op.parameters || [])
    .filter((p) => p.in === 'path')
    .map((p) => p.name);
}

function camelToKebab(s) {
  return s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function kebabToCamel(s) {
  return s.replace(/-(\w)/g, (_, c) => c.toUpperCase());
}

function optionFlag(field) {
  const kebab = camelToKebab(field.key);
  const desc = field.description || field.key;
  if (field.type === 'boolean' || field.enum?.every((v) => typeof v === 'boolean')) {
    return `      .option('--${kebab} <bool>', '${desc}')`;
  }
  if (field.isArray) {
    return `      .option('--${kebab} <items>', '${desc} (comma-separated)')`;
  }
  return `      .option('--${kebab} <value>', '${desc}')`;
}

function optionToBody(field) {
  const kebab = camelToKebab(field.key);
  const accessor = `opts['${kebab}']` ;
  if (field.type === 'boolean') {
    return `      if (${accessor} !== undefined) body.${field.key} = ${accessor} === 'true';`;
  }
  if (field.type === 'number' || field.type === 'integer') {
    return `      if (${accessor} !== undefined) body.${field.key} = Number(${accessor});`;
  }
  if (field.isArray) {
    return `      if (${accessor} !== undefined) body.${field.key} = ${accessor}.split(',').map(s => s.trim());`;
  }
  return `      if (${accessor} !== undefined) body.${field.key} = ${accessor};`;
}

// ── Route grouping ───────────────────────────────────────────────────

function groupRoutes(paths) {
  const groups = {};
  for (const [p, methods] of Object.entries(paths)) {
    // /v1/admin/game-payments/{id}/game-payment-items/{id} -> game-payments
    const parts = p.replace('/v1/admin/', '').split('/');
    const group = parts[0];
    if (!groups[group]) groups[group] = [];
    for (const [method, op] of Object.entries(methods)) {
      groups[group].push({ path: p, method, op, parts });
    }
  }
  return groups;
}

// ── Code generation ──────────────────────────────────────────────────

function generateGroup(groupName, routes, components) {
  const cmdName = groupName; // e.g. 'game-payments'
  const varName = groupName.replace(/-(\w)/g, (_, c) => c.toUpperCase()); // gamePayments
  const fnName = 'register' + varName.charAt(0).toUpperCase() + varName.slice(1); // registerGamePayments

  const lines = [
    `'use strict';`,
    ``,
    `// AUTO-GENERATED by scripts/codegen.js — do not edit manually`,
    ``,
    `const { get, post, put } = require('../api');`,
    `const { getBaseUrl } = require('../config');`,
    `const { table, ok, err, requireToken } = require('../output');`,
    ``,
  ];

  const actionLines = [];

  for (const route of routes) {
    const { path: routePath, method, op } = route;
    const summary = op.summary || op.operationId || routePath;
    const pathParams = getPathParams(op);
    const queryParams = getQueryParams(op);
    const bodyFields = getBodyFields(op, components);

    // Build sub-command name from path
    const subParts = routePath.replace('/v1/admin/', '').replace(groupName, '').replace(/^\//, '').split('/');
    const subName = subParts.filter((s) => !s.startsWith('{')).join('-') || '';

    // Determine command name
    // For sub-resources (e.g. game-payment-items), prefix with method to disambiguate
    // For trigger/action endpoints (no body), just use the sub-path name
    const methodPrefix = { get: 'list', post: 'create', put: 'update', delete: 'delete' }[method] || method;
    const hasBody = bodyFields.length > 0;
    let actionName;
    if (!subName) {
      actionName = methodPrefix;
    } else if (!hasBody && method === 'post') {
      // Trigger endpoints like recalculate-scores, calculate-ranks
      actionName = subName;
    } else {
      actionName = `${methodPrefix}-${subName}`;
    }

    const cmdArgs = pathParams.map((p) => `<${kebabToCamel(camelToKebab(p))}>`).join(' ');
    const fullCmdName = actionName;

    const a = [];
    a.push(`  // ${method.toUpperCase()} ${routePath}`);
    a.push(`  // ${summary}`);
    a.push(`  cmd`);

    const commandParts = [fullCmdName, cmdArgs].filter(Boolean).join(' ');
    a.push(`    .command('${commandParts}')`);
    a.push(`    .description('${summary.replace(/'/g, "\\'").slice(0, 80)}')`);

    // Query param options
    for (const qp of queryParams) {
      const kebab = camelToKebab(qp.key);
      const desc = qp.description || qp.key;
      if (qp.default !== undefined) {
        a.push(`    .option('--${kebab} <value>', '${desc}', '${qp.default}')`);
      } else {
        a.push(`    .option('--${kebab} <value>', '${desc}')`);
      }
    }

    // Body field options (for POST/PUT with body)
    if ((method === 'post' || method === 'put') && bodyFields.length > 0) {
      // Required fields as arguments, optional as options
      const requiredFields = bodyFields.filter((f) => f.required);
      const optionalFields = bodyFields.filter((f) => !f.required);
      for (const f of optionalFields) {
        a.push(optionFlag(f));
      }
    }

    const jsParams = pathParams.map(p => kebabToCamel(camelToKebab(p)));
    a.push(`    .action(async function (${jsParams.join(', ')}) {`);
    a.push(`      const config = this.parent.parent._v8config;`);
    a.push(`      requireToken(config);`);
    a.push(`      const base = getBaseUrl(config);`);

    if (method === 'get') {
      // Build query string
      if (queryParams.length > 0) {
        a.push(`      const opts = this.opts();`);
        a.push(`      const qs = new URLSearchParams();`);
        for (const qp of queryParams) {
          const kebab = camelToKebab(qp.key);
          a.push(`      if (opts['${kebab}'] !== undefined) qs.set('${qp.key}', opts['${kebab}']);`);
        }
        const pathWithParams = routePath.replace(/\{(\w+)\}/g, (_, name) => `\${${kebabToCamel(camelToKebab(name))}}`);
        a.push(`      const res = await get(base, \`${pathWithParams}?\${qs}\`, config.token);`);
      } else {
        const pathWithParams = routePath.replace(/\{(\w+)\}/g, (_, name) => `\${${kebabToCamel(camelToKebab(name))}}`);
        a.push(`      const res = await get(base, \`${pathWithParams}\`, config.token);`);
      }
      a.push(`      if (res.status !== 200) return err(\`\${res.status}: \${res.data.message || 'failed'}\`);`);
      a.push(`      if (this.parent.parent.opts().json) return console.log(JSON.stringify(res.data));`);
      a.push(`      console.log(JSON.stringify(res.data, null, 2));`);
    } else {
      // POST/PUT
      const bodyFields2 = getBodyFields(op, components);
      if (bodyFields2.length > 0) {
        a.push(`      const opts = this.opts();`);
        a.push(`      const body = {};`);
        for (const f of bodyFields2) {
          a.push(optionToBody(f));
        }
        const pathWithParams = routePath.replace(/\{(\w+)\}/g, (_, name) => `\${${kebabToCamel(camelToKebab(name))}}`);
        const httpMethod = method === 'put' ? 'put' : 'post';
        a.push(`      const res = await ${httpMethod}(base, \`${pathWithParams}\`, config.token, body);`);
      } else {
        const pathWithParams = routePath.replace(/\{(\w+)\}/g, (_, name) => `\${${kebabToCamel(camelToKebab(name))}}`);
        a.push(`      const res = await post(base, \`${pathWithParams}\`, config.token, {});`);
      }
      a.push(`      if (res.status !== 200 && res.status !== 201) return err(\`\${res.status}: \${res.data.message || 'failed'}\`);`);
      a.push(`      if (this.parent.parent.opts().json) return console.log(JSON.stringify(res.data));`);
      a.push(`      ok(JSON.stringify(res.data, null, 2));`);
    }

    a.push(`    });`);
    a.push(``);
    actionLines.push(a.join('\n'));
  }

  lines.push(`function ${fnName}(program) {`);
  lines.push(`  const cmd = program.command('${cmdName}').description('${cmdName} management');`);
  lines.push(``);
  lines.push(actionLines.join('\n'));
  lines.push(`}`);
  lines.push(``);
  lines.push(`module.exports = { ${fnName} };`);
  lines.push(``);

  return { fileName: `gen-${cmdName}.js`, content: lines.join('\n'), fnName };
}

// ── Main ─────────────────────────────────────────────────────────────

async function main() {
  let spec;
  const baseUrl = process.argv[2];
  if (baseUrl) {
    console.log(`Fetching spec from ${baseUrl}...`);
    spec = await fetchSpec(baseUrl);
    fs.writeFileSync(SPEC_FILE, JSON.stringify(spec, null, 2));
    console.log(`Saved spec to ${SPEC_FILE}`);
  } else {
    spec = JSON.parse(fs.readFileSync(SPEC_FILE, 'utf8'));
    console.log(`Using saved spec from ${SPEC_FILE}`);
  }

  const groups = groupRoutes(spec.paths);
  const generated = [];

  // Skip groups that already have hand-written commands
  const handWritten = new Set(['verse', 'users', 'credits', 'comments', 'coupon']);

  for (const [groupName, routes] of Object.entries(groups)) {
    if (handWritten.has(groupName)) {
      console.log(`  skip ${groupName} (hand-written)`);
      continue;
    }
    const result = generateGroup(groupName, routes, spec.components);
    const outPath = path.join(OUT_DIR, result.fileName);
    fs.writeFileSync(outPath, result.content);
    console.log(`  wrote ${result.fileName} (${routes.length} endpoints)`);
    generated.push(result);
  }

  // Generate registration snippet
  console.log('\n// Add to src/index.js:');
  for (const g of generated) {
    console.log(`const { ${g.fnName} } = require('./commands/${g.fileName.replace('.js', '')}');`);
  }
  console.log('');
  for (const g of generated) {
    console.log(`${g.fnName}(program);`);
  }
}

main().catch(console.error);
